### ISSUE TITLE
Organization singup page

### ISSUE THREAD

**Issue by RuthAnn1** [Eco-Friends-Connect/Eco-Friends#11]
This page is for the organization to sign-up to have a landing page in order to post their volunteer opportunities. 
Included:

- organization name 
- email address 
- first name 
- last name 
- password 
- reenter password

**Comment by dinaolmelak** [comment]
Would the organization have the `first_name`, `last_name`, and `password`?
- 🤔 I think this does bring up the question of who would be responsible from the organization for signing up on our website to post the organization posts.
