### ISSUE TITLE
Logout Button

### ISSUE THREAD

**Issue by Donnyd88** [Eco-Friends-Connect/Eco-Friends#122]
## Description

The site needs a logout button.

## Motivation

Users need to be able to logout

## Current Behavior

Users are unable to logout

## Proposed Solution

Create Button to use the /logout api route

**Comment by dinaolmelak** [comment]
I have fixed the `AuthContext`. I am currently reverting the changes I did for debugging the issue. I had commented out all the other places where it was used so that I can debug it. I will revert the changes I did and push to your branch @Donnyd88 👍🏽

**Comment by Donnyd88** [comment]
Nice. Thank you.
