### ISSUE TITLE
How does it works button

### ISSUE THREAD

**Issue by Kendiya242** [Eco-Friends-Connect/Eco-Friends#155]
## Description
When the user clicks the " how it works button" , it can redirect them to the how it works page that gives additional information about the website.

## Motivation

This feature is beneficial to give users a completed understanding about how the site works.

## Current Behavior

How it currently works on the website. How it works button is unresponsive.

## Proposed Solution

1.  The purpose of this feature is to get the " How is works button" to redirect to the how it works page.
2.  Also, to create a page describing the website.

## Code Snippet (Optional)

N/A

## Additional Information

N/A

**Comment by dinaolmelak** [comment]
@Kendiya242 , This ticket has been handled by @Donnyd88  on the following `Pull Request:` #161  You can see the changes on the [website](https://eco-friends-web.web.app/)
