### ISSUE TITLE
Volunteer search results component

### ISSUE THREAD

**Issue by dinaolmelak** [Eco-Friends-Connect/Eco-Friends#22]
## Description

This component is for the display of the results after searching with #21 . 

## Motivation

We would have to have the component for displaying that data.

## Current Behavior

Takes in the results of the search and displays the information along with the `<img>`

## Proposed Solution

- look through Figma to see how it looks like
- consider looking through the mongoose data models for better view.

## Code Snippet (Optional)

N/A

## Additional Information

N/A

**Comment by dinaolmelak** [comment]
Should the list of events be public ? or is it only the people who have account with `Eco-friends` be able to see the events?
@RuthAnn1 , @Donnyd88 , @Samueldnvn

**Comment by dinaolmelak** [comment]
@Donnyd88 , Are you referring to this ticket?

**Comment by Donnyd88** [comment]
Yes

**Comment by dinaolmelak** [comment]
I saw it , unclaimed 😅 I thought no one was doing it

**Comment by Donnyd88** [comment]
Sorry, I should have claimed it. Did you do a lot of work on it? :S

**Comment by dinaolmelak** [comment]
I can forfeit the ticket it, I just sat down to work more on it

**Comment by dinaolmelak** [comment]
I have disclaimed it 👍🏽

**Comment by Donnyd88** [comment]
Thank you. And sorry for your wasted time and effort.

**Comment by dinaolmelak** [comment]
No worries @Donnyd88, There is a lot to be done, so thank you for sharing the ticket load with us.
