### ISSUE TITLE
UserPage

### ISSUE THREAD

**Issue by RuthAnn1** [Eco-Friends-Connect/Eco-Friends#7]
This is the user's home page where they can see the events they have gone to along with the logged hours and badges they have earned.  This also should show the users upcoming events that they have singed up for.

**Comment by dinaolmelak** [comment]
@RuthAnn1 , What did you mean by `Logged hours`?

**Comment by RuthAnn1** [comment]
Logged hours was a thought we had earlier where the user can see the hours they have done.  But I think that is better suited for the badges page and not the user landing page.
